sbatch  bat0_0.sbat
sbatch  bat0_2.sbat
sbatch  bat0_4.sbat
sbatch  bat0_6.sbat
sbatch  bat0_8.sbat
sbatch  bat1_0.sbat
sbatch  bat1_2.sbat
sbatch  bat1_4.sbat
sbatch  bat1_6.sbat
sbatch  bat1_8.sbat
sbatch  bat2_0.sbat
sbatch  bat2_2.sbat
sbatch  bat2_4.sbat
sbatch  bat2_6.sbat
sbatch  bat2_8.sbat
sbatch  bat3_0.sbat
sbatch  bat3_2.sbat
sbatch  bat3_4.sbat
sbatch  bat3_6.sbat
sbatch  bat3_8.sbat
sbatch  bat4_0.sbat
sbatch  bat4_2.sbat
sbatch  bat4_4.sbat
sbatch  bat4_6.sbat
sbatch  bat4_8.sbat
sbatch  bat5_0.sbat
sbatch  bat5_2.sbat
sbatch  bat5_4.sbat
sbatch  bat5_6.sbat
sbatch  bat5_8.sbat
sbatch  bat6_0.sbat
sbatch  bat6_2.sbat
sbatch  bat6_4.sbat
sbatch  bat6_6.sbat
sbatch  bat6_8.sbat
sbatch  bat7_0.sbat
sbatch  bat7_2.sbat
sbatch  bat7_4.sbat
sbatch  bat7_6.sbat
sbatch  bat7_8.sbat
